### PR TITLE
New command, bugfixes and improvements

### PR DESCRIPTION
**Pull request by bennr01**
Yet another bunch of bugfixes for the `mc`-command, but also some improvements to the python-command.

**New Command and Files**
- `ftpserver` uses pyftpdlib to start a ftpserver. I frequently use omz`s ftpserver and tought it may be usefull to add to StaSh.
- added a helppage for the manpages. I tought it may be useful to document the behavior of the new `man`-command (in case others want to write manpages; i dont think my english is sufficent to write anything wich is not to hard to read)

**Improvements**
- The `python` command will now pass `_stash` and `__debug__` to the interactive interpreter.
- cleaned up the code of the `mc`-command by removing all unnecessary assignments in `except-clauses`.

**Bugfixes**
- Fixed a bug in `mc` where menu-entries were swapped. I accidently added this when cleaning up the menu-entries in `mc`  in an earlier commit.
- Fixed a bug in `mc` where no help was shown for a topic.

**Short info**
- I have updated the `getstash.py`-file in my fork, so testing this changes with `selfupdate -f bennr01:dev` should work now. I recently noticed that `seldupdate -f user:branch` wont work if the fork still contains the old `getstash.py`.

Also, a question: What do you think about the idea of adding a command for enabling and disabling monkeypatches for modules and functions not working in Pythonista? For example, patching `subprocessing` and `os.popen` to call the shell-commands in StaSh. The functions and modules i thought about patching dont work in Pythonista, so this could make more "normal" python-scripts compatible with Pythonista by using StaSh. Also, because they dont work by default, any weird behavior caused by monkeypatching should be acceptable because the scripts would still work more than by not doing any monkeypatching. The monkey-patching would be done by a command, which would have to be run by the user everytime he wants to enable them (they would be disabled by default and resetted whn Pythonista restarts).

### CODE REVIEW

**Comment by ywangd** [comment]
I already had monkey patch applied to the i/o streams, see https://github.com/ywangd/stash/blob/master/system/shiowrapper.py

Though normally I am not a fan of monkey patch, it is somehow inevitable and necessary in a confined environment like Pythonista. So it sounds alright to me to monkey patch things like `os.popen` etc, as you said they don't work before the patch anyway. Instead of a command to enable/disable the patches, it could be an configuration option that can be set in the stash config file (i.e. `.stash_config`), with default to be `disabled` (e.g. https://github.com/ywangd/stash/blob/master/stash.py#L52) and users can opt-in to enable it in their own config files.

**Comment by bennr01** [comment]
@ywangd Thanks for your response. While it would be more logical to make the monkey patching a configuration option in `.stash_config`, i think a command would be more flexible and a less hidden feature.
Some reasons why i think a command is more flexible:
   - Monkeypatches could be enabled and disabled without restarting StaSh
   - A command could do more than just enable and disable the monkeypatches, for example showing enabled monkeypatches
   - A command would be less hidden (StaSh has a lot of awesome features which are not easy to be found)
   - I planned on making the patches in a way they could be enabled/disabled individually. So a user could write something like `monkeylord enable os_popen`, `monkeylord disable ALL` or `monkeylord enable INSTABLE` (where ALL and INSTABLE would be groups). Unless we would create a whole section in `.stash_config`, this would become pretty messy in the config.

I will first try to write a few monkeypatches and later check both ways.

My current plan is to create a dir `/system/patches/` with a subdir `/system/patches/modules/`. `/system/patches/` would also be a package containing all monkeypatches as classes. `/system/patches/modules/` would contain modules not implemented in Pythonista, which would be enabled/disabled by modifying `sys.path`.

Is there a way of getting return/exit-codes from `_stash()`/`_stash.run()`? I tought about using `os.getenv("?")`, but with `persisten_level=2` the exit-codes would not be available, are they?
Thanks.

**Comment by ywangd** [comment]
@bennr01 OK if it is more than just a single boolean option, a command is more appropriate. 

Where is the directory `/lib/patches/` created? You won't be able to write against the actual root directory on iOS. Is the command name actually moneky**lord**? I thought it was monkey**load** from the first look of it and it made sense. But monkey**lord** is definitely much more interesting and humorous. 

Talking about hidden features, I have a few ideas to make StaSh more user friendly. First of them is to create a settings menu, similar to what Pythonista itself provides. So current config options and more can be specified via a GUI instead of going to the text file. However I am currently busy with other things and probably won't be able to work on it for quite some time.

It is so incredible that you read the code, noticed the `persistent_level` parameter and even how it is used. Sometimes I myself get confused about all the sub-shell business. This part of code took me quite a long time to sort out and it still not as polished as I had hoped for. Anyway, you can check the exit code of the call interface like the following:
```python
worker = _stash('some_command ...')
print worker.return_value  # this is the exit code
```

**Comment by bennr01** [comment]
@ywangd Thanks for the help with `worker.return_value`. I overlooked it, but instead found out about `worker.state.environ`.

I wanted to create the dir `/patches/` in the `/$STASH_ROOT/lib/` dir, not in the iOS root dir, otherwise `selfupdate` would not update the directory. Sorry if i wrote this in a confusing way.

I am not sure about the name yet. Some of the reasons I tought about using `monkeylord`:
   - A `monkeylord` would be someone commanding monkeys
   - It is more funny
   - The "monkeylord"  was a powerful unit in the strategy-game "Supreme Commander". While this is no real reason for naming a command like this, I tought someone might see it and laugh.

However, the name `monkeyload` would make more sense.
Should I use `monkeyloard` as a compromise?

There is another problem about the monkeypatching: Python2 and Python3 cross compatibility. I tought about this when you created the `universal` branch. You are probably trying to make a Py2 and Py3 compatible version of StaSh like discussed in #179 (at least the name "universal" suggests this). I am not sure how monkeypatching will work with two python versions. Python2 and Python3 have some different functions (`os.popen` is deprecated in python3) and like @dgelessus said in https://github.com/ywangd/stash/commit/de96ff0feccce2fde168cfc7f21c4d3726410085, some functions expect other argument-types in python3. In this case, maybe a config-option would make more sense than a command, because the monkeypatching would then be handled by the StaSh-core.

Talking about monkey-patching, should i try to patch `os.getpid` to return `ShBaseThread.job_id`? This may be usefull for monkeypatching some other functions like `os.kill`.

If you are busy i may be able to write a GUI for the settings. What kind of GUI would you like to add? A ´ui.View`/`dialogs`, some text-UI or a texteditor like vim mentioned in #118? A `ui.View` would be more user-friendly, but a text-ui would keep the terminal/shell feeling of StaSh. Should the GUI replace the command `stash_conf`?

**Comment by ywangd** [comment]
* I think `monkeylord` is good
* Python3 compatibility is still a long way ahead. So you probably don't need to worry about it for the time being. In worst-case, the mokeylord command can check the interpreter version and report it cannot function if the interpreter is Python 3.
* I am not sure about patching `os.getpid` as it currently does have a meaningful behaviour. I guess it really comes down to what you want to do with the patch. If the benefits is high, maybe it is OK.
* The settings GUI would be something similar to the Pythonista's settings dialog, not a text UI. Otherwise might as well just use `stashconf`. Yes it is meant to be a replacement of `stashconf` and more, things like changing the color scheme, button to add editor action for `launch_stash`. I'll probably add a stub implementation in the next a few days. So we have something more solid to talk about.

**Pull request merged**
