### PR TITLE
GitHub Actions: python-version: ["2.7", "3.6", "3.10"]

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
Now that pytest is running, we see:
```
================== 180 failed, 3 skipped, 1 warning in 27.31s ==================
```

**Comment by cclauss** [comment]
@bennr01 Can we please get this merged so that we can work on the failing pytests?

**Comment by bennr01** [comment]
Oh, sure. Sorry, I've been a bit preoccupied lately, so this took a while. I'll merge it.

BTW, I see that you changed the build env from ubuntu to macos, why?

Also, you may want to change the pytest command to `pytest tests/ --ignore=tests/system/data/ --showlocals --verbose --show-capture=all --log-level=debug` (taken from the travis file).

**Comment by cclauss** [comment]
macOS is closer to iOS especially when it comes to pbpaste.

**Pull request merged**
