### PR TITLE
Remove usage of non-inclusive language

### PR DESCRIPTION
**Pull request by ywangd**
This PR remove usages of non-inclusive language from the code base. We should also strive to not use them in future development. Thanks!

### CODE REVIEW

**Comment by ywangd** [comment]
The CI failed. But I don't think it is related to my changes. It failed to install a dependency (`zope.interface`) for `benterfaces`. I checked the CI history and noticed the same failure was there weeks ago for the `dev` branch. @bennr01  do you mind looking into it? Thanks!

Here is an excerpt of the failure message:
```
../test_pip.py:250: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../stashtest.py:184: in run_command
    self.assertEqual(
E   AssertionError: 1 != 0 : unexpected exitcode (0 expected, got 1)
E   Output:
E   Working on GitHub repository ...
E   Extracting archive file ...
E   Running setup file ...
E   Package installed: benterfaces-master
E   Installing dependency: zope.interface (required by: benterfaces-master)
E   Querying PyPI ... 
E   Using zope.interface==5.1.0...
E   A source distribution is available and will be used.
E   Downloading package ...
E   Extracting archive file ...
E   Running setup file ...
E   WARNING: Extension modules are skipped: [<__main__.OmniClass object at 0x7fc42f6af580>]
E   Package installed: zope.interface
E   stash: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/home/travis/build/ywangd/zope.interface/info.json'
E   Traceback (most recent call last):
E     File "/home/travis/build/ywangd/stash/system/shruntime.py", line 546, in exec_py_file
E       exec (code, namespace, namespace)
E     File "../../../bin/pip.py", line 1705, in <module>
E       repository.install(pkg_name, ver_spec, flags=flags, extras=extras)
E     File "../../../bin/pip.py", line 1471, in install
E       self._install('-'.join([repo, release]), pkg_info, archive_filename, dependency_flags=flags, extras=extras)
E     File "../../../bin/pip.py", line 1019, in _install
E       repository.install(dep_name, ver_spec, flags=dependency_flags, extras=extras)
E     File "../../../bin/pip.py", line 1295, in install
E       with open(info_file, 'w') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/ywangd/zope.interface/info.json'
```

**Comment by bennr01** [comment]
Seems like the changes in #417 may cause the problem, so it's not caused by this PR.


@DedSecer can you take a look at this bug? I am not too familiar with how you implemented the `pip show` command.

**Review by bennr01 — APPROVED** [review]

**Comment by cclauss** [comment]
@ywangd Can you please visit https://travis-ci.org/github/ywangd/stash and under `More options` select `Trigger build` on `master` to reenable the Travis CI tests?
```
tests/pip/test_pip.py::PipTests::test_install_github FAILED              [ 59%]
tests/pip/test_pip.py::PipTests::test_install_local PASSED               [ 60%]
tests/pip/test_pip.py::PipTests::test_install_pypi_complex_1 FAILED      [ 60%]
tests/pip/test_pip.py::PipTests::test_install_pypi_nobinary FAILED       [ 61%]
tests/pip/test_pip.py::PipTests::test_install_pypi_onlybinary FAILED     [ 61%]
tests/pip/test_pip.py::PipTests::test_install_pypi_simple_1 FAILED       [ 62%]
```

**Comment by cclauss** [comment]
Or you might need to https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/

**Comment by DedSecer** [comment]
Sorry for my missing this notifications.
`pip show` will download `info.json`which include the information of the package and save it to the `SITE_PACKAGES_FOLDER/PACKAGE_NAME_FOLDER`.
I will have a look a this error.

**Comment by DedSecer** [comment]
That's because pip installed a package call `zope.interface` but save the package to `SITE_PACKAGES_FOLDER/zope`  so pip can't find to folder `SITE_PACKAGES_FOLDER/zope.interface`.
so what about save the `info.json` to other folder?

**Comment by DedSecer** [comment]
I have changed `INFO_FILE_FODER` in #429

**Comment by ywangd** [comment]
Thanks @DedSecer for fixing the failure. CI is now back to green.

**Pull request merged**
