### PR TITLE
Adding sed.py to stash

### PR DESCRIPTION
**Pull request by fschaeck**
sed.py is a copy from my project fschaeck/PythonSed which is a fully compatible Python implementation of GNU sed 4.8 with some additions.

### CODE REVIEW

**Comment by fschaeck** [comment]
Anything wrong with this pull-request? The code works for Python 2 and 3 and all tests run fine...

**Comment by Aareon** [comment]
LGTM 👍

**Comment by fschaeck** [comment]
@ywangd Is this project dead or what is the reason for all those pull-request to be waiting here for over a year? If you don't find the time, maybe you can ask for someone to join as maintainer?

**Comment by Aareon** [comment]
@fschaeck its high time someone started an active fork

**Comment by ywangd** [comment]
@fschaeck Sorry for no response on the PRs. As you have noticed, the project has not really been maintained for a while. @bennr01 has kindly been the maintainer for quite some time after me. But it is now unmaintained again. I can invite you to be the maintainer if you are interested. So at least you can merge this PR on your own. You can also choose to fork this project. Please let me know. Thanks!

**Comment by fschaeck** [comment]
@ywangd Well… it doesn’t look like a full-time job once the current PRs are worked through. So, yes, if you give me the rights I‘ll take the role as a maintainer. I‘d rather do that than creating a fork!

**Comment by ywangd** [comment]
@fschaeck Invitation sent. Thanks for helping out!

**Pull request merged**
