### PR TITLE
Add gh github command

### PR DESCRIPTION
**Pull request by jsbain**
This adds a github (gh) command, with a fork, create, and pull (pull request) command.  This pull was created with the new command

### CODE REVIEW

**Comment by ywangd** [comment]
Thanks @jsbain This script is a cool addition to the git tools. I think it would be really beneficial to put up a post on the fourm to showcase the usages and an example lifecycle using all these tools. I can also write the tutorial. But since you are the author, it seems more appropriate for you to write it. :)

**Comment by jsbain** [comment]
yeah, i am writing something up, to include an end to end set of examples.

**Comment by ywangd** [comment]
By the way, this is now merged into the master branch.

On Thu, Feb 25, 2016 at 6:36 PM, jsbain <notifications@github.com> wrote:

> yeah, i am writing something up, to include an end to end set of examples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ywangd/stash/pull/164#issuecomment-188654353>.
>



-- 
----------------------------------------------------------------------
                      Life is elsewhere

**Comment by ywangd** [comment]
Just push a new commit with fix to some syntax bugs 66968a8ec16fccc17125cd29e2ecb834fcead840

**Pull request merged**
