### PR TITLE
Switch to the jsbain fork of dulwich (issue #106)

### PR DESCRIPTION
**Pull request by oefe**
This is an attempt at fixing issue #106 

Unfortunately, it is not as simple as exchanging the URL. We need also to check wether we are using the old version (by checking whether `fetch` is available), clean up the old versions, and reload `dulwich`

### CODE REVIEW

**Comment by oefe** [comment]
Oops, I committed another change in this branch that should probably go into a separate pull request. 

Let me know if I should separate these changes

**Comment by oefe** [comment]
Another (completely unrelated) thought: would it be better to make pull requests for the git command against @jsbain 's repository?

**Comment by ywangd** [comment]
@jsbain Could you please have a look at these changes since you are the author the `git` command?
@oefe I agree it is better to make pull requests for `git` command to @jsbain 's fork. Does it sound reasonable to you, @jsbain ?

**Comment by jsbain** [comment]
Either way re pull.   I'd suggest checking `dulwich.__version__`, rather than existence of `fetch`.  Transistor1 version was 0,9,8.  I updated my fork to be `(0,9,9,'jsbain_fork')`.   My eventual goal is to update the code in the git module to use the official dulwich versions, since there is really nothing needed in the fork ... Need to just update a few method signatures to use the original.  

Checking the version tuple will allow an easier way to specify which form we need.

**Comment by jsbain** [comment]
Ok, I've merged this change, along with a change to check for version.  This ended up being more difficult than I thought, because it is possible someone has dulwich in another folder, so it is necessary to delete all dulwich packages from sys.modules.  In retrospect, we should be deleting the libpath from sys.path after using it, and maybe importing dulwich using an alias, so that it doesn't stomp on anyone else's version.

I'll check in as soon as I detangle the mess I created when using merge in the strange state that resulted...

**Comment by jsbain** [comment]
https://github.com/ywangd/stash/pull/109

**Pull request merged**
