### PR TITLE
XML-RPC replacement #264

### PR DESCRIPTION
**Pull request by zrzka**
Replaces XML-RPC calls in pip, except package search. Can't find any endpoint and it looks like that people recommends to list simplified index and search in it. Time consuming, not an ideal solution, ... I think that we can live with XML-RPC & search for now. Package is listed immediately and rest is done via JSON.

### CODE REVIEW

**Comment by zrzka** [comment]
Ah, it's against master, not dev, will fix it.

**Comment by zrzka** [comment]
Please, do not merge yet. This PR contains quick fix to versions, but I'm going to optimize it now to avoid three requests to the same API endpoint (in `download` for example). I'll let you know when this PR will be ready.

**Comment by zrzka** [comment]
Feel free to merge. What's done in this PR:

* Fixed update
    * Same context manager wrapper as install, because it calls install internally
    * VersionSpecifier has wrong arguments
* XML-RPC replaced
    * In all functions, except search where I'm unable to find any JSON endpoint
* Optimize number of requests by reusing pkg_data (download function for example)

**Comment by jsbain** [comment]
@zrzka It seems you may need to update the tests so travis ci passes?

**Comment by zrzka** [comment]
@jsbain it's failing in test_threads.py. Sometimes passing, sometimes not. I did not investigate these tests because I thought rhat pip has nothing to do with them and someone is working on threads in dev. See the history https://travis-ci.org/ywangd/stash/pull_requests Green, red, green, ... Anyway, will check.

**Comment by ywangd** [comment]
@zrzka You are right. The threads test is not well written and behaves sometimes randomly.

**Pull request merged**
