### PR TITLE
Exclude special envvars from list, as discussed in #51

### PR DESCRIPTION
**Pull request by dgelessus**

### CODE REVIEW

**Comment by ywangd** [comment]
@dgelessus 
Thanks for the pull request. 
One comment: As `$N`, e.g. `$1`, is used for representing arguments to a shell script. It is possible that number of arguments is greater than 10. In this case, `$10`, `$11`, etc would also be created as special variables. On a command line, these variables have to be quoted like `${10}`. But in `os.environ`, they are just saved as `10`.

**Comment by dgelessus** [comment]
I'm not entirely sure if that is the case. A number of sources indicate that only $1 through $9 are used for positional parameters and anything above that would require use of `$@`, `$*` or `shift`, though for example the GNU Bash reference specifically allows use of one or more digits (though numbers with multiple digits need to use brace syntax).

**Comment by ywangd** [comment]
@dgelessus I didn't know that canonical Unix shell (sh) does not allow `$10` and up. But Bash for modern Linux including OS X do honour `$10` etc. So I think it is adequate for stash to support them as well. 

Check the first character of a variable like the follows
```python
vardict = {k: v for k, v in vardict if k[0] not in "$@?!#*0123456789"}
```
should be sufficient as it is impossible to enter a variable like `1A` from the command line.

**Comment by ywangd** [comment]
@dgelessus If above changes are OK with you, I'll merge the pull and make the changes. Or if you would make the changes, I'll just simply merge afterwards. Thanks!

**Comment by dgelessus** [comment]
Go ahead. I was thinking of adding a more complex check so names like ?foo wouln't be hidden, but that isn't worth the readability.

**Comment by ywangd** [comment]
I have also made another correction to `vardict`, so the code now reads `... k, v in verdict.items() ...`. Thanks!

**Comment by dgelessus** [comment]
Oops, I overlooked that. Thanks for fixing.

**Pull request merged**
