### PR TITLE
Replace Thread.isAlive() with Thread.is_alive()

### PR DESCRIPTION
**Pull request by cclauss**
`Thread.is_alive()` was added in ___Python 2.6___ so we can change `.isAlive()` to `.is_alive()` everywhere to be compatible with all versions of Pythonista.
* https://docs.python.org/2/library/threading.html#threading.Thread.is_alive
* https://github.com/ywangd/stash/pull/463#discussion_r1126007645

### CODE REVIEW

**Comment by cclauss** [comment]
@mkb79 Your review, please.

**Review by mkb79 — COMMENTED** [review]
Looks good to me. 

FYI:
`SUITextView` must be replaced with `SUITextView_PY3` on Python == 3.* in another PR. Otherwise Pythonista 3.4 still crashes.

**Comment by cclauss** [comment]
Yes.  I am trying to break #463 into bite-sized chunks so we can get it all merged.

**Review by mkb79 — APPROVED** [review]
Looks good!

**Comment by cclauss** [comment]
@bennr01 Migrated to `dev`

**Comment by cclauss** [comment]
Closing in favor of #478

**Pull request closed without merging**
